version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # PostgreSQL database (optional)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Django web application
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - logs_volume:/tmp
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://crm_user:crm_password@db:5432/crm_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery worker
  celery_worker:
    build: .
    volumes:
      - .:/app
      - logs_volume:/tmp
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://crm_user:crm_password@db:5432/crm_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    command: celery -A crm worker --loglevel=info

  # Celery beat scheduler
  celery_beat:
    build: .
    volumes:
      - .:/app
      - logs_volume:/tmp
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://crm_user:crm_password@db:5432/crm_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    command: celery -A crm beat --loglevel=info

volumes:
  postgres_data:
  redis_data:
  logs_volume:
